### ISSUE TITLE
when current directory contains arbitrary .yml files  the application dies with error

### ISSUE THREAD

**Issue by mvk** [mvk/sshadder#5]
example run:
```
cd ~/src/github.com/ansible_project/
sshadder
Enter master password: 
Traceback (most recent call last):
  File "/home/user/.virtualenvs/sshadder-dev/bin/sshadder", line 11, in <module>
    sys.exit(main())
  File "/home/user/.virtualenvs/sshadder-dev/local/lib/python2.7/site-packages/sshadder/sshadder.py", line 294, in main
    decryptor=simple_decryptor
  File "/home/user/.virtualenvs/sshadder-dev/local/lib/python2.7/site-packages/sshadder/sshadder.py", line 275, in add_keys
    decryptor(master_password, key_password_hashed)
  File "/home/user/.virtualenvs/sshadder-dev/local/lib/python2.7/site-packages/sshadder/sshadder.py", line 244, in simple_decryptor
    unwrapper(ciphertext)
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

```

:) funny bug

**Comment by mvk** [comment]
fixed.
